server:
  port: 9000

spring:
  application:
    name: catalog-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  
queue:
  movie:
    name: MovieQueue
    
message:"Movie loaded with success"
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

info:
  app:
    name: catalog-service
    description: Hola, soy el microservicio catalog.
    version: 1.0.0

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
