server:
  port: ${PORT:${SERVER_PORT:0}}

idRandom: ${random.value}

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27019
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  serie:
    name: SerieQueue

message: "series loaded with success"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

info:
  app:
    name: serie-service
    description: Hola, soy el microservicio serie.
    version: 1.0.0

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
